### ISSUE TITLE
Partial derivative of x * y not working

### ISSUE THREAD

**Issue by ajayyy** [nicoco007/Propagation-of-Uncertainty-Calculator#1]
It is resulting in zero.

**Comment by nicoco007** [comment]
Did you change the values in the *Variables* section to match the equation?

Here's an example:

![image](https://user-images.githubusercontent.com/1349975/65203191-fe4dce80-da58-11e9-9940-8c2b069fa3bd.png)

**Comment by ajayyy** [comment]
Ah, I didn't do `x * y`, I did `xy`.

![image](https://user-images.githubusercontent.com/12688112/65207315-3d7f1e00-da5f-11e9-8740-43aa1d299e33.png)


It seems this is to support variables with multiple letters, which is a nice feature.
